import { open, shot, check, section, selectText, BASE, L } from "./lib.mjs";
const { ctx, page } = await open();
await page.goto(BASE + L);
await page.waitForSelector(".cl-card-inline");

section("Links");
const [popup] = await Promise.all([ctx.waitForEvent("page"), page.locator('a[href^="https://www.rfc-editor.org"]').first().click()]);
check("External source link opens in a new tab on click (links.mjs)", popup.url().startsWith("https://www.rfc-editor.org"), popup.url());
await popup.close();

section("Card thread: persistence, follow-up, minimise");
check("Card and answer survive a reload (/api/state hydration)", (await page.locator(".cl-card-inline .cl-card-answer").first().innerText()).length > 40);
check("Pretest grade survives a reload", (await page.locator('form[data-quiz-id="pretest"] [data-cl-grade]').count()) === 1);
const card = page.locator(".cl-card-inline").first();
await card.locator("[data-cl-followup]").fill("So for hashed filenames like style.3f9a.css, would I use the opposite policy?");
await card.locator("[data-cl-followup-form] button[type=submit]").click();
await page.waitForSelector(".cl-card-turn-followup");
check("Follow-up appended to the same card thread", (await card.locator(".cl-card-turn").count()) === 2);
console.log("waiting for follow-up answer…");
await page.waitForSelector(".cl-card-turn-followup .cl-card-answer:not(:has(.cl-spinner))", { timeout: 600000 });
const fu = (await card.locator(".cl-card-turn-followup .cl-card-answer").innerText()).trim();
check("Follow-up answered in the thread with full context", fu.length > 40, `${fu.slice(0, 90).replace(/\n/g, " ")}…`);
await card.scrollIntoViewIfNeeded();
await shot(page, "10-card-followup");
await card.locator("[data-cl-minimise]").click();
check("Minimise collapses the card to a margin badge", (await card.isHidden()) && (await page.locator(".cl-badge-marker").first().isVisible()));
await page.locator(".cl-badge-marker").first().scrollIntoViewIfNeeded();
await shot(page, "11-card-minimised");
await page.locator(".cl-badge-marker").first().click();
check("Badge reopens the card", await card.isVisible());

section("Graded quiz with confidence ratings");
const quiz = page.locator('form[data-quiz-id="check-1"]');
check("Graded quiz gets Sure/Unsure/Guessing controls", (await quiz.locator(".cl-confidence").count()) === 2);
await quiz.locator('input[name="q1"][value="a"]').check();
await quiz.locator('.cl-q[data-question-id="q1"] input[data-cl-confidence][value="sure"]').check();
await quiz.locator('textarea[name="q2"]').fill("Send Cache-Control: no-cache. The cache sends If-None-Match: \"css-v1\". If unchanged the server replies 304 Not Modified and the cache reuses its copy; if changed it gets a 200 with the new CSS and a new ETag.");
await quiz.locator('.cl-q[data-question-id="q2"] input[data-cl-confidence][value="unsure"]').check();
await quiz.scrollIntoViewIfNeeded();
await shot(page, "12-quiz-filled");
await quiz.locator(".cl-submit").click();
console.log("waiting for grade…");
await page.waitForSelector('form[data-quiz-id="check-1"] [data-cl-grade]', { timeout: 600000 });
const score = (await quiz.locator(".cl-grade-score").innerText()).trim();
check("Quiz graded inline by the agent", /\d+%/.test(score), score);
check("Per-question verdicts rendered", (await quiz.locator(".cl-q-verdict").count()) === 2);
check("Retake button offered after grading", (await quiz.locator("[data-cl-retake]").count()) === 1);
await quiz.scrollIntoViewIfNeeded();
await shot(page, "13-quiz-graded", { fullPage: false });
await quiz.screenshot({ path: "/tmp/pi-teach-e2e/shots/13b-quiz-graded-full.png" });
await ctx.close();
