import { open, shot, check, pi, piState, BASE, L } from "./lib.mjs";
import fs from "node:fs";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const offset = Number(fs.readFileSync("ui.offset", "utf8"));
await pi("/classroom");
await sleep(2500);
const notice = fs.readFileSync("ui.log").subarray(offset).toString("utf8").split("\n").filter(Boolean)
  .map((l) => JSON.parse(l)).filter((r) => r.method === "notify").map((r) => r.message);
check("New session's /classroom mentions the waiting question", notice.some((m) => /question/i.test(m)), notice.find((m) => /question/i.test(m))?.replace(/\n/g, " "));
const { ctx, page } = await open();
await page.goto(BASE + L);
await page.locator(".cl-card-inline").first().waitFor();
check("Reloaded lesson shows the leftover question still pending", (await page.locator(".cl-card-answer .cl-spinner").count()) === 1);
const settled = (await piState()).settled;
await pi("/teach http-caching-headers");
console.log("waiting for /teach to pick up the leftover question…");
await page.waitForFunction(() => document.querySelectorAll(".cl-card-answer .cl-spinner").length === 0, null, { timeout: 600000 });
const cards = page.locator(".cl-card-inline");
const lastCard = cards.nth((await cards.count()) - 1);
const last = (await lastCard.locator(".cl-card-answer").innerText()).trim();
check("/teach in the new session claimed and answered it; card updated live over SSE", last.length > 40, `${last.slice(0, 90).replace(/\n/g, " ")}…`);
await lastCard.scrollIntoViewIfNeeded();
await shot(page, "20-recovered-answer");
for (let i = 0; i < 600 && (await piState()).settled === settled; i++) await sleep(1000);
const ev = fs.readFileSync("events.jsonl", "utf8").split("\n").filter((l) => l.includes('"type":"agent_end"')).pop();
const teach = JSON.parse(ev).messages.find((m) => m.role === "user")?.content?.map((c) => c.text).join("") ?? "";
check("/teach brief carries the computed snapshot (scores, review state, missed questions)", /snapshot|review/i.test(teach) && /0%|missed/i.test(teach));
fs.writeFileSync("teach-brief.txt", teach);
await ctx.close();
