import { open, shot, check, section, pi, piState, BASE, L } from "./lib.mjs";
import fs from "node:fs";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
section("Spaced review schedule");
const { ctx, page } = await open();
await page.goto(BASE + "/c/http-caching-headers");
check("Failed attempt from 2 days ago (attempts backdated on disk) → lesson shows 'review due'", await page.locator(".cl-badge-review").isVisible());
await shot(page, "21-review-due");

section("Offline export");
const offset = fs.statSync("ui.log").size;
await pi("/classroom export http-caching-headers");
await sleep(3000);
const notes = fs.readFileSync("ui.log").subarray(offset).toString("utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.method === "notify").map((r) => r.message);
check("/classroom export reports the written index", notes.some((m) => /_exports/.test(m)), notes.join(" ").replace(/\n/g, " ").slice(0, 160));
const root = "/tmp/pi-teach-e2e/classrooms/_exports/http-caching-headers";
const files = fs.readdirSync(root, { recursive: true }).map(String);
check("Export has index.html and lessons/<slug>.html", files.includes("index.html") && files.some((f) => /^lessons\/001-freshness-before-revalidation\.html$/.test(f)), files.filter((f) => f.endsWith(".html")).join(", "));
check("Export never contains quiz/ (answer key, submissions)", !files.some((f) => /(^|\/)quiz(\/|$)|key\.json/.test(f)));
const lessonHtml = fs.readFileSync(`${root}/lessons/001-freshness-before-revalidation.html`, "utf8");
check("Exported lesson has a UTF-8 BOM", lessonHtml.charCodeAt(0) === 0xfeff);
await page.goto(`file://${root}/index.html`);
await shot(page, "22-export-index", { fullPage: true });
await page.goto(`file://${root}/lessons/001-freshness-before-revalidation.html`);
const text = await page.locator("body").innerText();
check("Exported lesson includes the question threads and grades, readable offline", /hashed filenames/i.test(text) && /CDN/i.test(text) && /%/.test(text));
await page.getByText(/hashed filenames/i).first().scrollIntoViewIfNeeded();
await shot(page, "23-export-lesson");
await ctx.close();
