import { open, check, section, pi, BASE, L } from "./lib.mjs";
import fs from "node:fs";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
section("Deleting a card, status widget, stopping the server");
const { ctx, page } = await open();
await page.goto(BASE + L);
await page.locator(".cl-card-inline").first().waitFor();
const before = await page.locator(".cl-card-inline").count();
await page.locator(".cl-card-inline [data-cl-delete]").last().click();
await page.locator(".cl-confirm [data-cl-confirm]").click();
await sleep(800);
await page.reload(); await page.locator(".cl-card-inline").first().waitFor();
check("Confirmed delete removes the card and its highlight, persisted", (await page.locator(".cl-card-inline").count()) === before - 1);
await ctx.close();
const widgets = fs.readFileSync("ui.log", "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.method === "setWidget");
check("Status widget reads 'classroom server running on port 4199'", widgets.some((w) => (w.widgetLines ?? []).join("").replace(/\x1b\[[0-9;]*m/g, "").includes("server running on port 4199")));
const n = widgets.length;
await pi("/classroom stop"); await sleep(1500);
const after = fs.readFileSync("ui.log", "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.method === "setWidget");
const down = await fetch(BASE + "/").then(() => false, () => true);
check("/classroom stop closes the server and clears the widget", down && after.length > n && !after[after.length - 1].widgetLines);
